#!/bin/bash -e

export PATH=/var/vcap/packages/ruby-2.1.6-intel/bin:$PATH
RUN_DIR=/var/vcap/sys/run/uaa-intel
LOG_DIR=/var/vcap/sys/log/uaa-intel
PIDFILE=$RUN_DIR/cf-registrar.pid
VCAP_COMMON_PATH=/var/vcap/packages/uaa-intel/vcap-common

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "VCAP registrar"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    chown vcap:vcap $RUN_DIR
    chown -R vcap:vcap $LOG_DIR

    echo $$ > $PIDFILE
    chown vcap:vcap $PIDFILE

    export CONFIG_FILE=/var/vcap/jobs/uaa-intel/config/cf-registrar/config.yml

    cd $VCAP_COMMON_PATH
    exec chpst -u vcap:vcap /var/vcap/packages/ruby-2.1.6-intel/bin/bundle exec \
         $VCAP_COMMON_PATH/bin/cf-registrar \
         --register-with-router \
         --register-varz-credentials

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: cf-registrar_ctl {start|stop}" ;;

esac
exit 0
